### PR TITLE
Update egress.yaml

### PR DESCRIPTION
**Pull request by whites11**
Give internet access to all pods in giantswarm namespace in default policies

### Testing

Description on how cilium can be tested.

- [ ] fresh install works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM
- [ ] upgrade from previous version works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM

#### Other testing

Description of features to additionally test for cilium installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by kopiczko** [comment]
Is that enough? Why not all egress?

**Comment by whites11** [comment]
> Is that enough? Why not all egress?

This is all external egress:

> The world entity corresponds to all endpoints outside of the cluster. Allowing to world is identical to allowing to CIDR 0.0.0.0/0. An alternative to allowing from and to world is to define fine grained DNS or CIDR based policies.

Wether that's enough or not, I'll leave @fiunchinho to ensure that.

**Comment by kopiczko** [comment]
Yeah but only in `giantswarm`.

**Comment by whites11** [comment]
@fiunchinho I think I was suggesting this to fix some CAPI problem.
I don't remember though, so I'll assign this PR to you

**Comment by kopiczko** [comment]
This message on Slack from @mnitchev suggests we need to open it in both namespaces https://gigantic.slack.com/archives/C03LV8E0RL7/p1664875316503909?thread_ts=1664532424.015859&cid=C03LV8E0RL7

I'm happy to approve it if you open `kube-system` as well.

**Comment by whites11** [comment]
If you're referring to me, please feel free to take over, change test and merge yourself. I'm not working on this any more it does not make much sense for me to do that.

**Comment by fiunchinho** [comment]
A couple of days ago we discussed about adding cilium network policies to the apps that would require egress traffic, rather than open the whole namespace. This alternative approach comes as a result of [the concerns expressed by team shield](https://github.com/giantswarm/giantswarm/issues/23014#issuecomment-1212500514).

**Comment by kopiczko** [comment]
> A couple of days ago we discussed about adding cilium network policies to the apps that would require egress traffic, rather than open the whole namespace. This alternative approach comes as a result of [the concerns expressed by team shield](https://github.com/giantswarm/giantswarm/issues/23014#issuecomment-1212500514).

I like that but that shouldn't stop the ongoing work. I'll take over this PR.

**Review by AverageMarcus — APPROVED** [review]

**Pull request merged**
