### PR TITLE
Added default network policies

### PR DESCRIPTION
**Pull request by AverageMarcus**
This PR:

- Adds default policies for allowing egress to all and allowing ingress into kube-system namespace from host

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by tfussell** [comment]
I don't think this will work because the CRDs are installed by the cilium operator, but this helm release will fail until that is running. We'll need to install network policies in a post-install hook or install CRDs in a separate app or pre-install hook.

**Comment by AverageMarcus** [comment]
I didn't realise that! That clears things up a bit more.

Post-install might not work as the operator would need to have been created, image pulled and running before the CRDs are in place.

I guess a different app is the only way to go.

**Comment by tfussell** [comment]
@AverageMarcus FYI we already have https://github.com/giantswarm/cluster-resources-app which contains similar network policies.

**Comment by AverageMarcus** [comment]
That's where I took them from, but I thought it'd be nicer if we could ship them with Cilium itself to keep things more specific.

Yeah, post-install for this is just messy. Ideally, some functionality would be built into the operator for this but as it's not our app that's not gonna happen.

**Pull request closed without merging**
